// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeFdHpzoTMVVfgd_MjDM92IL2DBy75BDI',
    appId: '1:526103764084:web:83716fe403650503cac521',
    messagingSenderId: '526103764084',
    projectId: 'moto-black',
    authDomain: 'moto-black.firebaseapp.com',
    databaseURL: 'https://moto-black-default-rtdb.firebaseio.com',
    storageBucket: 'moto-black.appspot.com',
    measurementId: 'G-8BP6RD63ND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNpnM7xYxUpsW34aBdlnhqvtI3YWGY9Kg',
    appId: '1:526103764084:android:95b379237b1028b9cac521',
    messagingSenderId: '526103764084',
    projectId: 'moto-black',
    databaseURL: 'https://moto-black-default-rtdb.firebaseio.com',
    storageBucket: 'moto-black.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6J8Z4K8vaoksMpefSSaBemp8m2CfN678',
    appId: '1:526103764084:ios:7a4abb1acd45c96ccac521',
    messagingSenderId: '526103764084',
    projectId: 'moto-black',
    databaseURL: 'https://moto-black-default-rtdb.firebaseio.com',
    storageBucket: 'moto-black.appspot.com',
    iosBundleId: 'com.example.appMotoblackMototaxista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6J8Z4K8vaoksMpefSSaBemp8m2CfN678',
    appId: '1:526103764084:ios:866074ea69aeea56cac521',
    messagingSenderId: '526103764084',
    projectId: 'moto-black',
    databaseURL: 'https://moto-black-default-rtdb.firebaseio.com',
    storageBucket: 'moto-black.appspot.com',
    iosBundleId: 'com.example.appMotoblackMototaxista.RunnerTests',
  );
}
